image: python:3.8-slim

variables:
    DEBIAN_FRONTEND: noninteractive
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - test
    - bench
    - post

before_script:
    - apt-get update && apt-get install -y build-essential
    - pip install pipenv
    - pipenv install --system --dev --skip-lock


test:
    stage: test
    script:
        - pygount --format cloc-xml -o loc.xml josie
        - pytest
    artifacts:
        paths: 
            - "*.xml"
        expire_in: 1 week

.benchmark:
    stage: bench
    dependencies: 
        - test
    before_script:
        - apt-get update && apt-get -y install git
        - pip install pipenv
    script: 
        - git fetch origin master
        - git checkout origin/master
        - pipenv install --system --dev --skip-lock
        - pytest --bench 
        - git checkout $CI_COMMIT_REF_NAME
        - pipenv install --system --dev --skip-lock
        - pytest --bench --benchmark-compare=0001 --benchmark-compare-fail=min:10%
    only:
        - merge_requests

pages:
    stage: post
    script: 
        - |
            apt-get update && apt-get -y install texlive texlive-science \
            texlive-latex-extra
        - invoke docs
    artifacts:
        paths:
            - public
    only:
        - master

badges:
    stage: post
    dependencies:
        - test
    before_script: 
        - apt-get update && apt-get -y install git
    script: 
        - git fetch --all --tags
        - pip install badgey
        - badgey LOCBadge loc.xml
        - badgey CoverageBadge cov.xml
        - badgey GitVersionBadge .
    artifacts:
        paths:
            - "*.svg"
    only:
        - master
