image: python:slim

variables:
    DEBIAN_FRONTEND: noninteractive

stages:
    - test
    - bench
    - post

before_script:
    - pip install ".[all]"


test:
    stage: test
    script:
        - pip install pygount
        - pygount --format cloc-xml -o loc.xml
        - pytest
    artifacts:
        paths: 
            - "*.xml"
        expire_in: 1 week

benchmark:
    stage: bench
    dependencies: 
        - test
    script: 
        - git checkout master
        - pip install -e ".[all]"
        - pytest --bench 
        - git checkout $CI_COMMIT_REF_NAME
        - pip install -e ".[all]"
        - pytest --bench --benchmark-compare=0001
    except:
        - master

pages:
    stage: post
    script: 
        - |
            apt-get update && apt-get -y install texlive texlive-science \
            texlive-latex-extra
        - invoke docs
        - ls -l docs/build
        - mv docs/build/* public
    artifacts:
        paths:
            - public
    only:
        - master

badges:
    stage: post
    dependencies:
        - test
    before_script: 
        - apt-get update && apt-get -y install git
    script: 
        - git fetch --all --tags
        - pip install badgey
        - badgey LOCBadge loc.xml
        - badgey CoverageBadge cov.xml
        - badgey GitVersionBadge .
    artifacts:
        paths:
            - "*.svg"
    only:
        - master
