image: python:slim

variables:
    DEBIAN_FRONTEND: noninteractive

stages:
    - test
    - post


test:
    stage: test
    script:
        - pip install pygount
        - pygount --format cloc-xml -o loc.xml
        - pip install ".[all]"
        - pytest
    artifacts:
        paths: 
            - "*.xml"
        expire_in: 1 week

pages:
    before_script: 
        - |
            apt-get update && apt-get -y install texlive texlive-science \
            texlive-latex-extra
        - mkdir -p "public/$CI_COMMIT_REF_SLUG"
        - pip install ".[docs]"
    script: 
        - invoke docs
        - ls -l docs/build
        - mv docs/build/* public
    artifacts:
        paths:
            - public
    only:
        - master

badges:
    stage: post
    dependencies:
        - test
    before_script: 
        - apt-get update && apt-get -y install git
    script: 
        - git fetch --all --tags
        - pip install badgey
        - badgey LOCBadge loc.xml
        - badgey CoverageBadge cov.xml
        - badgey GitVersionBadge .
    artifacts:
        paths:
            - "*.svg"
    only:
        - master
